#include-once
Func GPL()
Local $licensetext
$licensetext=$licensetext&"                    GNU GENERAL PUBLIC LICENSE"&@CRLF
$licensetext=$licensetext&"                       Version 3, 29 June 2007"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&" Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>"&@CRLF
$licensetext=$licensetext&" Everyone is permitted to copy and distribute verbatim copies"&@CRLF
$licensetext=$licensetext&" of this license document, but changing it is not allowed."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"                            Preamble"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The GNU General Public License is a free, copyleft license for"&@CRLF
$licensetext=$licensetext&"software and other kinds of works."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The licenses for most software and other practical works are designed"&@CRLF
$licensetext=$licensetext&"to take away your freedom to share and change the works.  By contrast,"&@CRLF
$licensetext=$licensetext&"the GNU General Public License is intended to guarantee your freedom to"&@CRLF
$licensetext=$licensetext&"share and change all versions of a program--to make sure it remains free"&@CRLF
$licensetext=$licensetext&"software for all its users.  We, the Free Software Foundation, use the"&@CRLF
$licensetext=$licensetext&"GNU General Public License for most of our software; it applies also to"&@CRLF
$licensetext=$licensetext&"any other work released this way by its authors.  You can apply it to"&@CRLF
$licensetext=$licensetext&"your programs, too."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  When we speak of free software, we are referring to freedom, not"&@CRLF
$licensetext=$licensetext&"price.  Our General Public Licenses are designed to make sure that you"&@CRLF
$licensetext=$licensetext&"have the freedom to distribute copies of free software (and charge for"&@CRLF
$licensetext=$licensetext&"them if you wish), that you receive source code or can get it if you"&@CRLF
$licensetext=$licensetext&"want it, that you can change the software or use pieces of it in new"&@CRLF
$licensetext=$licensetext&"free programs, and that you know you can do these things."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  To protect your rights, we need to prevent others from denying you"&@CRLF
$licensetext=$licensetext&"these rights or asking you to surrender the rights.  Therefore, you have"&@CRLF
$licensetext=$licensetext&"certain responsibilities if you distribute copies of the software, or if"&@CRLF
$licensetext=$licensetext&"you modify it: responsibilities to respect the freedom of others."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  For example, if you distribute copies of such a program, whether"&@CRLF
$licensetext=$licensetext&"gratis or for a fee, you must pass on to the recipients the same"&@CRLF
$licensetext=$licensetext&"freedoms that you received.  You must make sure that they, too, receive"&@CRLF
$licensetext=$licensetext&"or can get the source code.  And you must show them these terms so they"&@CRLF
$licensetext=$licensetext&"know their rights."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Developers that use the GNU GPL protect your rights with two steps:"&@CRLF
$licensetext=$licensetext&"(1) assert copyright on the software, and (2) offer you this License"&@CRLF
$licensetext=$licensetext&"giving you legal permission to copy, distribute and/or modify it."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  For the developers' and authors' protection, the GPL clearly explains"&@CRLF
$licensetext=$licensetext&"that there is no warranty for this free software.  For both users' and"&@CRLF
$licensetext=$licensetext&"authors' sake, the GPL requires that modified versions be marked as"&@CRLF
$licensetext=$licensetext&"changed, so that their problems will not be attributed erroneously to"&@CRLF
$licensetext=$licensetext&"authors of previous versions."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Some devices are designed to deny users access to install or run"&@CRLF
$licensetext=$licensetext&"modified versions of the software inside them, although the manufacturer"&@CRLF
$licensetext=$licensetext&"can do so.  This is fundamentally incompatible with the aim of"&@CRLF
$licensetext=$licensetext&"protecting users' freedom to change the software.  The systematic"&@CRLF
$licensetext=$licensetext&"pattern of such abuse occurs in the area of products for individuals to"&@CRLF
$licensetext=$licensetext&"use, which is precisely where it is most unacceptable.  Therefore, we"&@CRLF
$licensetext=$licensetext&"have designed this version of the GPL to prohibit the practice for those"&@CRLF
$licensetext=$licensetext&"products.  If such problems arise substantially in other domains, we"&@CRLF
$licensetext=$licensetext&"stand ready to extend this provision to those domains in future versions"&@CRLF
$licensetext=$licensetext&"of the GPL, as needed to protect the freedom of users."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Finally, every program is threatened constantly by software patents."&@CRLF
$licensetext=$licensetext&"States should not allow patents to restrict development and use of"&@CRLF
$licensetext=$licensetext&"software on general-purpose computers, but in those that do, we wish to"&@CRLF
$licensetext=$licensetext&"avoid the special danger that patents applied to a free program could"&@CRLF
$licensetext=$licensetext&"make it effectively proprietary.  To prevent this, the GPL assures that"&@CRLF
$licensetext=$licensetext&"patents cannot be used to render the program non-free."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The precise terms and conditions for copying, distribution and"&@CRLF
$licensetext=$licensetext&"modification follow."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"                       TERMS AND CONDITIONS"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  0. Definitions."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  ""This License"" refers to version 3 of the GNU General Public License."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  ""Copyright"" also means copyright-like laws that apply to other kinds of"&@CRLF
$licensetext=$licensetext&"works, such as semiconductor masks."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  ""The Program"" refers to any copyrightable work licensed under this"&@CRLF
$licensetext=$licensetext&"License.  Each licensee is addressed as ""you"".  ""Licensees"" and"&@CRLF
$licensetext=$licensetext&"""recipients"" may be individuals or organizations."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  To ""modify"" a work means to copy from or adapt all or part of the work"&@CRLF
$licensetext=$licensetext&"in a fashion requiring copyright permission, other than the making of an"&@CRLF
$licensetext=$licensetext&"exact copy.  The resulting work is called a ""modified version"" of the"&@CRLF
$licensetext=$licensetext&"earlier work or a work ""based on"" the earlier work."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  A ""covered work"" means either the unmodified Program or a work based"&@CRLF
$licensetext=$licensetext&"on the Program."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  To ""propagate"" a work means to do anything with it that, without"&@CRLF
$licensetext=$licensetext&"permission, would make you directly or secondarily liable for"&@CRLF
$licensetext=$licensetext&"infringement under applicable copyright law, except executing it on a"&@CRLF
$licensetext=$licensetext&"computer or modifying a private copy.  Propagation includes copying,"&@CRLF
$licensetext=$licensetext&"distribution (with or without modification), making available to the"&@CRLF
$licensetext=$licensetext&"public, and in some countries other activities as well."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  To ""convey"" a work means any kind of propagation that enables other"&@CRLF
$licensetext=$licensetext&"parties to make or receive copies.  Mere interaction with a user through"&@CRLF
$licensetext=$licensetext&"a computer network, with no transfer of a copy, is not conveying."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  An interactive user interface displays ""Appropriate Legal Notices"""&@CRLF
$licensetext=$licensetext&"to the extent that it includes a convenient and prominently visible"&@CRLF
$licensetext=$licensetext&"feature that (1) displays an appropriate copyright notice, and (2)"&@CRLF
$licensetext=$licensetext&"tells the user that there is no warranty for the work (except to the"&@CRLF
$licensetext=$licensetext&"extent that warranties are provided), that licensees may convey the"&@CRLF
$licensetext=$licensetext&"work under this License, and how to view a copy of this License.  If"&@CRLF
$licensetext=$licensetext&"the interface presents a list of user commands or options, such as a"&@CRLF
$licensetext=$licensetext&"menu, a prominent item in the list meets this criterion."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  1. Source Code."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The ""source code"" for a work means the preferred form of the work"&@CRLF
$licensetext=$licensetext&"for making modifications to it.  ""Object code"" means any non-source"&@CRLF
$licensetext=$licensetext&"form of a work."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  A ""Standard Interface"" means an interface that either is an official"&@CRLF
$licensetext=$licensetext&"standard defined by a recognized standards body, or, in the case of"&@CRLF
$licensetext=$licensetext&"interfaces specified for a particular programming language, one that"&@CRLF
$licensetext=$licensetext&"is widely used among developers working in that language."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The ""System Libraries"" of an executable work include anything, other"&@CRLF
$licensetext=$licensetext&"than the work as a whole, that (a) is included in the normal form of"&@CRLF
$licensetext=$licensetext&"packaging a Major Component, but which is not part of that Major"&@CRLF
$licensetext=$licensetext&"Component, and (b) serves only to enable use of the work with that"&@CRLF
$licensetext=$licensetext&"Major Component, or to implement a Standard Interface for which an"&@CRLF
$licensetext=$licensetext&"implementation is available to the public in source code form.  A"&@CRLF
$licensetext=$licensetext&"""Major Component"", in this context, means a major essential component"&@CRLF
$licensetext=$licensetext&"(kernel, window system, and so on) of the specific operating system"&@CRLF
$licensetext=$licensetext&"(if any) on which the executable work runs, or a compiler used to"&@CRLF
$licensetext=$licensetext&"produce the work, or an object code interpreter used to run it."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The ""Corresponding Source"" for a work in object code form means all"&@CRLF
$licensetext=$licensetext&"the source code needed to generate, install, and (for an executable"&@CRLF
$licensetext=$licensetext&"work) run the object code and to modify the work, including scripts to"&@CRLF
$licensetext=$licensetext&"control those activities.  However, it does not include the work's"&@CRLF
$licensetext=$licensetext&"System Libraries, or general-purpose tools or generally available free"&@CRLF
$licensetext=$licensetext&"programs which are used unmodified in performing those activities but"&@CRLF
$licensetext=$licensetext&"which are not part of the work.  For example, Corresponding Source"&@CRLF
$licensetext=$licensetext&"includes interface definition files associated with source files for"&@CRLF
$licensetext=$licensetext&"the work, and the source code for shared libraries and dynamically"&@CRLF
$licensetext=$licensetext&"linked subprograms that the work is specifically designed to require,"&@CRLF
$licensetext=$licensetext&"such as by intimate data communication or control flow between those"&@CRLF
$licensetext=$licensetext&"subprograms and other parts of the work."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The Corresponding Source need not include anything that users"&@CRLF
$licensetext=$licensetext&"can regenerate automatically from other parts of the Corresponding"&@CRLF
$licensetext=$licensetext&"Source."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The Corresponding Source for a work in source code form is that"&@CRLF
$licensetext=$licensetext&"same work."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  2. Basic Permissions."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  All rights granted under this License are granted for the term of"&@CRLF
$licensetext=$licensetext&"copyright on the Program, and are irrevocable provided the stated"&@CRLF
$licensetext=$licensetext&"conditions are met.  This License explicitly affirms your unlimited"&@CRLF
$licensetext=$licensetext&"permission to run the unmodified Program.  The output from running a"&@CRLF
$licensetext=$licensetext&"covered work is covered by this License only if the output, given its"&@CRLF
$licensetext=$licensetext&"content, constitutes a covered work.  This License acknowledges your"&@CRLF
$licensetext=$licensetext&"rights of fair use or other equivalent, as provided by copyright law."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  You may make, run and propagate covered works that you do not"&@CRLF
$licensetext=$licensetext&"convey, without conditions so long as your license otherwise remains"&@CRLF
$licensetext=$licensetext&"in force.  You may convey covered works to others for the sole purpose"&@CRLF
$licensetext=$licensetext&"of having them make modifications exclusively for you, or provide you"&@CRLF
$licensetext=$licensetext&"with facilities for running those works, provided that you comply with"&@CRLF
$licensetext=$licensetext&"the terms of this License in conveying all material for which you do"&@CRLF
$licensetext=$licensetext&"not control copyright.  Those thus making or running the covered works"&@CRLF
$licensetext=$licensetext&"for you must do so exclusively on your behalf, under your direction"&@CRLF
$licensetext=$licensetext&"and control, on terms that prohibit them from making any copies of"&@CRLF
$licensetext=$licensetext&"your copyrighted material outside their relationship with you."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Conveying under any other circumstances is permitted solely under"&@CRLF
$licensetext=$licensetext&"the conditions stated below.  Sublicensing is not allowed; section 10"&@CRLF
$licensetext=$licensetext&"makes it unnecessary."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  3. Protecting Users' Legal Rights From Anti-Circumvention Law."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  No covered work shall be deemed part of an effective technological"&@CRLF
$licensetext=$licensetext&"measure under any applicable law fulfilling obligations under article"&@CRLF
$licensetext=$licensetext&"11 of the WIPO copyright treaty adopted on 20 December 1996, or"&@CRLF
$licensetext=$licensetext&"similar laws prohibiting or restricting circumvention of such"&@CRLF
$licensetext=$licensetext&"measures."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  When you convey a covered work, you waive any legal power to forbid"&@CRLF
$licensetext=$licensetext&"circumvention of technological measures to the extent such circumvention"&@CRLF
$licensetext=$licensetext&"is effected by exercising rights under this License with respect to"&@CRLF
$licensetext=$licensetext&"the covered work, and you disclaim any intention to limit operation or"&@CRLF
$licensetext=$licensetext&"modification of the work as a means of enforcing, against the work's"&@CRLF
$licensetext=$licensetext&"users, your or third parties' legal rights to forbid circumvention of"&@CRLF
$licensetext=$licensetext&"technological measures."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  4. Conveying Verbatim Copies."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  You may convey verbatim copies of the Program's source code as you"&@CRLF
$licensetext=$licensetext&"receive it, in any medium, provided that you conspicuously and"&@CRLF
$licensetext=$licensetext&"appropriately publish on each copy an appropriate copyright notice;"&@CRLF
$licensetext=$licensetext&"keep intact all notices stating that this License and any"&@CRLF
$licensetext=$licensetext&"non-permissive terms added in accord with section 7 apply to the code;"&@CRLF
$licensetext=$licensetext&"keep intact all notices of the absence of any warranty; and give all"&@CRLF
$licensetext=$licensetext&"recipients a copy of this License along with the Program."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  You may charge any price or no price for each copy that you convey,"&@CRLF
$licensetext=$licensetext&"and you may offer support or warranty protection for a fee."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  5. Conveying Modified Source Versions."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  You may convey a work based on the Program, or the modifications to"&@CRLF
$licensetext=$licensetext&"produce it from the Program, in the form of source code under the"&@CRLF
$licensetext=$licensetext&"terms of section 4, provided that you also meet all of these conditions:"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    a) The work must carry prominent notices stating that you modified"&@CRLF
$licensetext=$licensetext&"    it, and giving a relevant date."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    b) The work must carry prominent notices stating that it is"&@CRLF
$licensetext=$licensetext&"    released under this License and any conditions added under section"&@CRLF
$licensetext=$licensetext&"    7.  This requirement modifies the requirement in section 4 to"&@CRLF
$licensetext=$licensetext&"    ""keep intact all notices""."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    c) You must license the entire work, as a whole, under this"&@CRLF
$licensetext=$licensetext&"    License to anyone who comes into possession of a copy.  This"&@CRLF
$licensetext=$licensetext&"    License will therefore apply, along with any applicable section 7"&@CRLF
$licensetext=$licensetext&"    additional terms, to the whole of the work, and all its parts,"&@CRLF
$licensetext=$licensetext&"    regardless of how they are packaged.  This License gives no"&@CRLF
$licensetext=$licensetext&"    permission to license the work in any other way, but it does not"&@CRLF
$licensetext=$licensetext&"    invalidate such permission if you have separately received it."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    d) If the work has interactive user interfaces, each must display"&@CRLF
$licensetext=$licensetext&"    Appropriate Legal Notices; however, if the Program has interactive"&@CRLF
$licensetext=$licensetext&"    interfaces that do not display Appropriate Legal Notices, your"&@CRLF
$licensetext=$licensetext&"    work need not make them do so."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  A compilation of a covered work with other separate and independent"&@CRLF
$licensetext=$licensetext&"works, which are not by their nature extensions of the covered work,"&@CRLF
$licensetext=$licensetext&"and which are not combined with it such as to form a larger program,"&@CRLF
$licensetext=$licensetext&"in or on a volume of a storage or distribution medium, is called an"&@CRLF
$licensetext=$licensetext&"""aggregate"" if the compilation and its resulting copyright are not"&@CRLF
$licensetext=$licensetext&"used to limit the access or legal rights of the compilation's users"&@CRLF
$licensetext=$licensetext&"beyond what the individual works permit.  Inclusion of a covered work"&@CRLF
$licensetext=$licensetext&"in an aggregate does not cause this License to apply to the other"&@CRLF
$licensetext=$licensetext&"parts of the aggregate."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  6. Conveying Non-Source Forms."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  You may convey a covered work in object code form under the terms"&@CRLF
$licensetext=$licensetext&"of sections 4 and 5, provided that you also convey the"&@CRLF
$licensetext=$licensetext&"machine-readable Corresponding Source under the terms of this License,"&@CRLF
$licensetext=$licensetext&"in one of these ways:"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    a) Convey the object code in, or embodied in, a physical product"&@CRLF
$licensetext=$licensetext&"    (including a physical distribution medium), accompanied by the"&@CRLF
$licensetext=$licensetext&"    Corresponding Source fixed on a durable physical medium"&@CRLF
$licensetext=$licensetext&"    customarily used for software interchange."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    b) Convey the object code in, or embodied in, a physical product"&@CRLF
$licensetext=$licensetext&"    (including a physical distribution medium), accompanied by a"&@CRLF
$licensetext=$licensetext&"    written offer, valid for at least three years and valid for as"&@CRLF
$licensetext=$licensetext&"    long as you offer spare parts or customer support for that product"&@CRLF
$licensetext=$licensetext&"    model, to give anyone who possesses the object code either (1) a"&@CRLF
$licensetext=$licensetext&"    copy of the Corresponding Source for all the software in the"&@CRLF
$licensetext=$licensetext&"    product that is covered by this License, on a durable physical"&@CRLF
$licensetext=$licensetext&"    medium customarily used for software interchange, for a price no"&@CRLF
$licensetext=$licensetext&"    more than your reasonable cost of physically performing this"&@CRLF
$licensetext=$licensetext&"    conveying of source, or (2) access to copy the"&@CRLF
$licensetext=$licensetext&"    Corresponding Source from a network server at no charge."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    c) Convey individual copies of the object code with a copy of the"&@CRLF
$licensetext=$licensetext&"    written offer to provide the Corresponding Source.  This"&@CRLF
$licensetext=$licensetext&"    alternative is allowed only occasionally and noncommercially, and"&@CRLF
$licensetext=$licensetext&"    only if you received the object code with such an offer, in accord"&@CRLF
$licensetext=$licensetext&"    with subsection 6b."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    d) Convey the object code by offering access from a designated"&@CRLF
$licensetext=$licensetext&"    place (gratis or for a charge), and offer equivalent access to the"&@CRLF
$licensetext=$licensetext&"    Corresponding Source in the same way through the same place at no"&@CRLF
$licensetext=$licensetext&"    further charge.  You need not require recipients to copy the"&@CRLF
$licensetext=$licensetext&"    Corresponding Source along with the object code.  If the place to"&@CRLF
$licensetext=$licensetext&"    copy the object code is a network server, the Corresponding Source"&@CRLF
$licensetext=$licensetext&"    may be on a different server (operated by you or a third party)"&@CRLF
$licensetext=$licensetext&"    that supports equivalent copying facilities, provided you maintain"&@CRLF
$licensetext=$licensetext&"    clear directions next to the object code saying where to find the"&@CRLF
$licensetext=$licensetext&"    Corresponding Source.  Regardless of what server hosts the"&@CRLF
$licensetext=$licensetext&"    Corresponding Source, you remain obligated to ensure that it is"&@CRLF
$licensetext=$licensetext&"    available for as long as needed to satisfy these requirements."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    e) Convey the object code using peer-to-peer transmission, provided"&@CRLF
$licensetext=$licensetext&"    you inform other peers where the object code and Corresponding"&@CRLF
$licensetext=$licensetext&"    Source of the work are being offered to the general public at no"&@CRLF
$licensetext=$licensetext&"    charge under subsection 6d."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  A separable portion of the object code, whose source code is excluded"&@CRLF
$licensetext=$licensetext&"from the Corresponding Source as a System Library, need not be"&@CRLF
$licensetext=$licensetext&"included in conveying the object code work."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  A ""User Product"" is either (1) a ""consumer product"", which means any"&@CRLF
$licensetext=$licensetext&"tangible personal property which is normally used for personal, family,"&@CRLF
$licensetext=$licensetext&"or household purposes, or (2) anything designed or sold for incorporation"&@CRLF
$licensetext=$licensetext&"into a dwelling.  In determining whether a product is a consumer product,"&@CRLF
$licensetext=$licensetext&"doubtful cases shall be resolved in favor of coverage.  For a particular"&@CRLF
$licensetext=$licensetext&"product received by a particular user, ""normally used"" refers to a"&@CRLF
$licensetext=$licensetext&"typical or common use of that class of product, regardless of the status"&@CRLF
$licensetext=$licensetext&"of the particular user or of the way in which the particular user"&@CRLF
$licensetext=$licensetext&"actually uses, or expects or is expected to use, the product.  A product"&@CRLF
$licensetext=$licensetext&"is a consumer product regardless of whether the product has substantial"&@CRLF
$licensetext=$licensetext&"commercial, industrial or non-consumer uses, unless such uses represent"&@CRLF
$licensetext=$licensetext&"the only significant mode of use of the product."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  ""Installation Information"" for a User Product means any methods,"&@CRLF
$licensetext=$licensetext&"procedures, authorization keys, or other information required to install"&@CRLF
$licensetext=$licensetext&"and execute modified versions of a covered work in that User Product from"&@CRLF
$licensetext=$licensetext&"a modified version of its Corresponding Source.  The information must"&@CRLF
$licensetext=$licensetext&"suffice to ensure that the continued functioning of the modified object"&@CRLF
$licensetext=$licensetext&"code is in no case prevented or interfered with solely because"&@CRLF
$licensetext=$licensetext&"modification has been made."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  If you convey an object code work under this section in, or with, or"&@CRLF
$licensetext=$licensetext&"specifically for use in, a User Product, and the conveying occurs as"&@CRLF
$licensetext=$licensetext&"part of a transaction in which the right of possession and use of the"&@CRLF
$licensetext=$licensetext&"User Product is transferred to the recipient in perpetuity or for a"&@CRLF
$licensetext=$licensetext&"fixed term (regardless of how the transaction is characterized), the"&@CRLF
$licensetext=$licensetext&"Corresponding Source conveyed under this section must be accompanied"&@CRLF
$licensetext=$licensetext&"by the Installation Information.  But this requirement does not apply"&@CRLF
$licensetext=$licensetext&"if neither you nor any third party retains the ability to install"&@CRLF
$licensetext=$licensetext&"modified object code on the User Product (for example, the work has"&@CRLF
$licensetext=$licensetext&"been installed in ROM)."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The requirement to provide Installation Information does not include a"&@CRLF
$licensetext=$licensetext&"requirement to continue to provide support service, warranty, or updates"&@CRLF
$licensetext=$licensetext&"for a work that has been modified or installed by the recipient, or for"&@CRLF
$licensetext=$licensetext&"the User Product in which it has been modified or installed.  Access to a"&@CRLF
$licensetext=$licensetext&"network may be denied when the modification itself materially and"&@CRLF
$licensetext=$licensetext&"adversely affects the operation of the network or violates the rules and"&@CRLF
$licensetext=$licensetext&"protocols for communication across the network."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Corresponding Source conveyed, and Installation Information provided,"&@CRLF
$licensetext=$licensetext&"in accord with this section must be in a format that is publicly"&@CRLF
$licensetext=$licensetext&"documented (and with an implementation available to the public in"&@CRLF
$licensetext=$licensetext&"source code form), and must require no special password or key for"&@CRLF
$licensetext=$licensetext&"unpacking, reading or copying."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  7. Additional Terms."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  ""Additional permissions"" are terms that supplement the terms of this"&@CRLF
$licensetext=$licensetext&"License by making exceptions from one or more of its conditions."&@CRLF
$licensetext=$licensetext&"Additional permissions that are applicable to the entire Program shall"&@CRLF
$licensetext=$licensetext&"be treated as though they were included in this License, to the extent"&@CRLF
$licensetext=$licensetext&"that they are valid under applicable law.  If additional permissions"&@CRLF
$licensetext=$licensetext&"apply only to part of the Program, that part may be used separately"&@CRLF
$licensetext=$licensetext&"under those permissions, but the entire Program remains governed by"&@CRLF
$licensetext=$licensetext&"this License without regard to the additional permissions."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  When you convey a copy of a covered work, you may at your option"&@CRLF
$licensetext=$licensetext&"remove any additional permissions from that copy, or from any part of"&@CRLF
$licensetext=$licensetext&"it.  (Additional permissions may be written to require their own"&@CRLF
$licensetext=$licensetext&"removal in certain cases when you modify the work.)  You may place"&@CRLF
$licensetext=$licensetext&"additional permissions on material, added by you to a covered work,"&@CRLF
$licensetext=$licensetext&"for which you have or can give appropriate copyright permission."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Notwithstanding any other provision of this License, for material you"&@CRLF
$licensetext=$licensetext&"add to a covered work, you may (if authorized by the copyright holders of"&@CRLF
$licensetext=$licensetext&"that material) supplement the terms of this License with terms:"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    a) Disclaiming warranty or limiting liability differently from the"&@CRLF
$licensetext=$licensetext&"    terms of sections 15 and 16 of this License; or"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    b) Requiring preservation of specified reasonable legal notices or"&@CRLF
$licensetext=$licensetext&"    author attributions in that material or in the Appropriate Legal"&@CRLF
$licensetext=$licensetext&"    Notices displayed by works containing it; or"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    c) Prohibiting misrepresentation of the origin of that material, or"&@CRLF
$licensetext=$licensetext&"    requiring that modified versions of such material be marked in"&@CRLF
$licensetext=$licensetext&"    reasonable ways as different from the original version; or"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    d) Limiting the use for publicity purposes of names of licensors or"&@CRLF
$licensetext=$licensetext&"    authors of the material; or"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    e) Declining to grant rights under trademark law for use of some"&@CRLF
$licensetext=$licensetext&"    trade names, trademarks, or service marks; or"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    f) Requiring indemnification of licensors and authors of that"&@CRLF
$licensetext=$licensetext&"    material by anyone who conveys the material (or modified versions of"&@CRLF
$licensetext=$licensetext&"    it) with contractual assumptions of liability to the recipient, for"&@CRLF
$licensetext=$licensetext&"    any liability that these contractual assumptions directly impose on"&@CRLF
$licensetext=$licensetext&"    those licensors and authors."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  All other non-permissive additional terms are considered ""further"&@CRLF
$licensetext=$licensetext&"restrictions"" within the meaning of section 10.  If the Program as you"&@CRLF
$licensetext=$licensetext&"received it, or any part of it, contains a notice stating that it is"&@CRLF
$licensetext=$licensetext&"governed by this License along with a term that is a further"&@CRLF
$licensetext=$licensetext&"restriction, you may remove that term.  If a license document contains"&@CRLF
$licensetext=$licensetext&"a further restriction but permits relicensing or conveying under this"&@CRLF
$licensetext=$licensetext&"License, you may add to a covered work material governed by the terms"&@CRLF
$licensetext=$licensetext&"of that license document, provided that the further restriction does"&@CRLF
$licensetext=$licensetext&"not survive such relicensing or conveying."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  If you add terms to a covered work in accord with this section, you"&@CRLF
$licensetext=$licensetext&"must place, in the relevant source files, a statement of the"&@CRLF
$licensetext=$licensetext&"additional terms that apply to those files, or a notice indicating"&@CRLF
$licensetext=$licensetext&"where to find the applicable terms."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Additional terms, permissive or non-permissive, may be stated in the"&@CRLF
$licensetext=$licensetext&"form of a separately written license, or stated as exceptions;"&@CRLF
$licensetext=$licensetext&"the above requirements apply either way."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  8. Termination."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  You may not propagate or modify a covered work except as expressly"&@CRLF
$licensetext=$licensetext&"provided under this License.  Any attempt otherwise to propagate or"&@CRLF
$licensetext=$licensetext&"modify it is void, and will automatically terminate your rights under"&@CRLF
$licensetext=$licensetext&"this License (including any patent licenses granted under the third"&@CRLF
$licensetext=$licensetext&"paragraph of section 11)."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  However, if you cease all violation of this License, then your"&@CRLF
$licensetext=$licensetext&"license from a particular copyright holder is reinstated (a)"&@CRLF
$licensetext=$licensetext&"provisionally, unless and until the copyright holder explicitly and"&@CRLF
$licensetext=$licensetext&"finally terminates your license, and (b) permanently, if the copyright"&@CRLF
$licensetext=$licensetext&"holder fails to notify you of the violation by some reasonable means"&@CRLF
$licensetext=$licensetext&"prior to 60 days after the cessation."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Moreover, your license from a particular copyright holder is"&@CRLF
$licensetext=$licensetext&"reinstated permanently if the copyright holder notifies you of the"&@CRLF
$licensetext=$licensetext&"violation by some reasonable means, this is the first time you have"&@CRLF
$licensetext=$licensetext&"received notice of violation of this License (for any work) from that"&@CRLF
$licensetext=$licensetext&"copyright holder, and you cure the violation prior to 30 days after"&@CRLF
$licensetext=$licensetext&"your receipt of the notice."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Termination of your rights under this section does not terminate the"&@CRLF
$licensetext=$licensetext&"licenses of parties who have received copies or rights from you under"&@CRLF
$licensetext=$licensetext&"this License.  If your rights have been terminated and not permanently"&@CRLF
$licensetext=$licensetext&"reinstated, you do not qualify to receive new licenses for the same"&@CRLF
$licensetext=$licensetext&"material under section 10."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  9. Acceptance Not Required for Having Copies."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  You are not required to accept this License in order to receive or"&@CRLF
$licensetext=$licensetext&"run a copy of the Program.  Ancillary propagation of a covered work"&@CRLF
$licensetext=$licensetext&"occurring solely as a consequence of using peer-to-peer transmission"&@CRLF
$licensetext=$licensetext&"to receive a copy likewise does not require acceptance.  However,"&@CRLF
$licensetext=$licensetext&"nothing other than this License grants you permission to propagate or"&@CRLF
$licensetext=$licensetext&"modify any covered work.  These actions infringe copyright if you do"&@CRLF
$licensetext=$licensetext&"not accept this License.  Therefore, by modifying or propagating a"&@CRLF
$licensetext=$licensetext&"covered work, you indicate your acceptance of this License to do so."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  10. Automatic Licensing of Downstream Recipients."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Each time you convey a covered work, the recipient automatically"&@CRLF
$licensetext=$licensetext&"receives a license from the original licensors, to run, modify and"&@CRLF
$licensetext=$licensetext&"propagate that work, subject to this License.  You are not responsible"&@CRLF
$licensetext=$licensetext&"for enforcing compliance by third parties with this License."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  An ""entity transaction"" is a transaction transferring control of an"&@CRLF
$licensetext=$licensetext&"organization, or substantially all assets of one, or subdividing an"&@CRLF
$licensetext=$licensetext&"organization, or merging organizations.  If propagation of a covered"&@CRLF
$licensetext=$licensetext&"work results from an entity transaction, each party to that"&@CRLF
$licensetext=$licensetext&"transaction who receives a copy of the work also receives whatever"&@CRLF
$licensetext=$licensetext&"licenses to the work the party's predecessor in interest had or could"&@CRLF
$licensetext=$licensetext&"give under the previous paragraph, plus a right to possession of the"&@CRLF
$licensetext=$licensetext&"Corresponding Source of the work from the predecessor in interest, if"&@CRLF
$licensetext=$licensetext&"the predecessor has it or can get it with reasonable efforts."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  You may not impose any further restrictions on the exercise of the"&@CRLF
$licensetext=$licensetext&"rights granted or affirmed under this License.  For example, you may"&@CRLF
$licensetext=$licensetext&"not impose a license fee, royalty, or other charge for exercise of"&@CRLF
$licensetext=$licensetext&"rights granted under this License, and you may not initiate litigation"&@CRLF
$licensetext=$licensetext&"(including a cross-claim or counterclaim in a lawsuit) alleging that"&@CRLF
$licensetext=$licensetext&"any patent claim is infringed by making, using, selling, offering for"&@CRLF
$licensetext=$licensetext&"sale, or importing the Program or any portion of it."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  11. Patents."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  A ""contributor"" is a copyright holder who authorizes use under this"&@CRLF
$licensetext=$licensetext&"License of the Program or a work on which the Program is based.  The"&@CRLF
$licensetext=$licensetext&"work thus licensed is called the contributor's ""contributor version""."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  A contributor's ""essential patent claims"" are all patent claims"&@CRLF
$licensetext=$licensetext&"owned or controlled by the contributor, whether already acquired or"&@CRLF
$licensetext=$licensetext&"hereafter acquired, that would be infringed by some manner, permitted"&@CRLF
$licensetext=$licensetext&"by this License, of making, using, or selling its contributor version,"&@CRLF
$licensetext=$licensetext&"but do not include claims that would be infringed only as a"&@CRLF
$licensetext=$licensetext&"consequence of further modification of the contributor version.  For"&@CRLF
$licensetext=$licensetext&"purposes of this definition, ""control"" includes the right to grant"&@CRLF
$licensetext=$licensetext&"patent sublicenses in a manner consistent with the requirements of"&@CRLF
$licensetext=$licensetext&"this License."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Each contributor grants you a non-exclusive, worldwide, royalty-free"&@CRLF
$licensetext=$licensetext&"patent license under the contributor's essential patent claims, to"&@CRLF
$licensetext=$licensetext&"make, use, sell, offer for sale, import and otherwise run, modify and"&@CRLF
$licensetext=$licensetext&"propagate the contents of its contributor version."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  In the following three paragraphs, a ""patent license"" is any express"&@CRLF
$licensetext=$licensetext&"agreement or commitment, however denominated, not to enforce a patent"&@CRLF
$licensetext=$licensetext&"(such as an express permission to practice a patent or covenant not to"&@CRLF
$licensetext=$licensetext&"sue for patent infringement).  To ""grant"" such a patent license to a"&@CRLF
$licensetext=$licensetext&"party means to make such an agreement or commitment not to enforce a"&@CRLF
$licensetext=$licensetext&"patent against the party."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  If you convey a covered work, knowingly relying on a patent license,"&@CRLF
$licensetext=$licensetext&"and the Corresponding Source of the work is not available for anyone"&@CRLF
$licensetext=$licensetext&"to copy, free of charge and under the terms of this License, through a"&@CRLF
$licensetext=$licensetext&"publicly available network server or other readily accessible means,"&@CRLF
$licensetext=$licensetext&"then you must either (1) cause the Corresponding Source to be so"&@CRLF
$licensetext=$licensetext&"available, or (2) arrange to deprive yourself of the benefit of the"&@CRLF
$licensetext=$licensetext&"patent license for this particular work, or (3) arrange, in a manner"&@CRLF
$licensetext=$licensetext&"consistent with the requirements of this License, to extend the patent"&@CRLF
$licensetext=$licensetext&"license to downstream recipients.  ""Knowingly relying"" means you have"&@CRLF
$licensetext=$licensetext&"actual knowledge that, but for the patent license, your conveying the"&@CRLF
$licensetext=$licensetext&"covered work in a country, or your recipient's use of the covered work"&@CRLF
$licensetext=$licensetext&"in a country, would infringe one or more identifiable patents in that"&@CRLF
$licensetext=$licensetext&"country that you have reason to believe are valid."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  If, pursuant to or in connection with a single transaction or"&@CRLF
$licensetext=$licensetext&"arrangement, you convey, or propagate by procuring conveyance of, a"&@CRLF
$licensetext=$licensetext&"covered work, and grant a patent license to some of the parties"&@CRLF
$licensetext=$licensetext&"receiving the covered work authorizing them to use, propagate, modify"&@CRLF
$licensetext=$licensetext&"or convey a specific copy of the covered work, then the patent license"&@CRLF
$licensetext=$licensetext&"you grant is automatically extended to all recipients of the covered"&@CRLF
$licensetext=$licensetext&"work and works based on it."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  A patent license is ""discriminatory"" if it does not include within"&@CRLF
$licensetext=$licensetext&"the scope of its coverage, prohibits the exercise of, or is"&@CRLF
$licensetext=$licensetext&"conditioned on the non-exercise of one or more of the rights that are"&@CRLF
$licensetext=$licensetext&"specifically granted under this License.  You may not convey a covered"&@CRLF
$licensetext=$licensetext&"work if you are a party to an arrangement with a third party that is"&@CRLF
$licensetext=$licensetext&"in the business of distributing software, under which you make payment"&@CRLF
$licensetext=$licensetext&"to the third party based on the extent of your activity of conveying"&@CRLF
$licensetext=$licensetext&"the work, and under which the third party grants, to any of the"&@CRLF
$licensetext=$licensetext&"parties who would receive the covered work from you, a discriminatory"&@CRLF
$licensetext=$licensetext&"patent license (a) in connection with copies of the covered work"&@CRLF
$licensetext=$licensetext&"conveyed by you (or copies made from those copies), or (b) primarily"&@CRLF
$licensetext=$licensetext&"for and in connection with specific products or compilations that"&@CRLF
$licensetext=$licensetext&"contain the covered work, unless you entered into that arrangement,"&@CRLF
$licensetext=$licensetext&"or that patent license was granted, prior to 28 March 2007."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Nothing in this License shall be construed as excluding or limiting"&@CRLF
$licensetext=$licensetext&"any implied license or other defenses to infringement that may"&@CRLF
$licensetext=$licensetext&"otherwise be available to you under applicable patent law."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  12. No Surrender of Others' Freedom."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  If conditions are imposed on you (whether by court order, agreement or"&@CRLF
$licensetext=$licensetext&"otherwise) that contradict the conditions of this License, they do not"&@CRLF
$licensetext=$licensetext&"excuse you from the conditions of this License.  If you cannot convey a"&@CRLF
$licensetext=$licensetext&"covered work so as to satisfy simultaneously your obligations under this"&@CRLF
$licensetext=$licensetext&"License and any other pertinent obligations, then as a consequence you may"&@CRLF
$licensetext=$licensetext&"not convey it at all.  For example, if you agree to terms that obligate you"&@CRLF
$licensetext=$licensetext&"to collect a royalty for further conveying from those to whom you convey"&@CRLF
$licensetext=$licensetext&"the Program, the only way you could satisfy both those terms and this"&@CRLF
$licensetext=$licensetext&"License would be to refrain entirely from conveying the Program."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  13. Use with the GNU Affero General Public License."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Notwithstanding any other provision of this License, you have"&@CRLF
$licensetext=$licensetext&"permission to link or combine any covered work with a work licensed"&@CRLF
$licensetext=$licensetext&"under version 3 of the GNU Affero General Public License into a single"&@CRLF
$licensetext=$licensetext&"combined work, and to convey the resulting work.  The terms of this"&@CRLF
$licensetext=$licensetext&"License will continue to apply to the part which is the covered work,"&@CRLF
$licensetext=$licensetext&"but the special requirements of the GNU Affero General Public License,"&@CRLF
$licensetext=$licensetext&"section 13, concerning interaction through a network will apply to the"&@CRLF
$licensetext=$licensetext&"combination as such."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  14. Revised Versions of this License."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The Free Software Foundation may publish revised and/or new versions of"&@CRLF
$licensetext=$licensetext&"the GNU General Public License from time to time.  Such new versions will"&@CRLF
$licensetext=$licensetext&"be similar in spirit to the present version, but may differ in detail to"&@CRLF
$licensetext=$licensetext&"address new problems or concerns."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Each version is given a distinguishing version number.  If the"&@CRLF
$licensetext=$licensetext&"Program specifies that a certain numbered version of the GNU General"&@CRLF
$licensetext=$licensetext&"Public License ""or any later version"" applies to it, you have the"&@CRLF
$licensetext=$licensetext&"option of following the terms and conditions either of that numbered"&@CRLF
$licensetext=$licensetext&"version or of any later version published by the Free Software"&@CRLF
$licensetext=$licensetext&"Foundation.  If the Program does not specify a version number of the"&@CRLF
$licensetext=$licensetext&"GNU General Public License, you may choose any version ever published"&@CRLF
$licensetext=$licensetext&"by the Free Software Foundation."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  If the Program specifies that a proxy can decide which future"&@CRLF
$licensetext=$licensetext&"versions of the GNU General Public License can be used, that proxy's"&@CRLF
$licensetext=$licensetext&"public statement of acceptance of a version permanently authorizes you"&@CRLF
$licensetext=$licensetext&"to choose that version for the Program."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  Later license versions may give you additional or different"&@CRLF
$licensetext=$licensetext&"permissions.  However, no additional obligations are imposed on any"&@CRLF
$licensetext=$licensetext&"author or copyright holder as a result of your choosing to follow a"&@CRLF
$licensetext=$licensetext&"later version."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  15. Disclaimer of Warranty."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY"&@CRLF
$licensetext=$licensetext&"APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT"&@CRLF
$licensetext=$licensetext&"HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM ""AS IS"" WITHOUT WARRANTY"&@CRLF
$licensetext=$licensetext&"OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,"&@CRLF
$licensetext=$licensetext&"THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR"&@CRLF
$licensetext=$licensetext&"PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM"&@CRLF
$licensetext=$licensetext&"IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF"&@CRLF
$licensetext=$licensetext&"ALL NECESSARY SERVICING, REPAIR OR CORRECTION."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  16. Limitation of Liability."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING"&@CRLF
$licensetext=$licensetext&"WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS"&@CRLF
$licensetext=$licensetext&"THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY"&@CRLF
$licensetext=$licensetext&"GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE"&@CRLF
$licensetext=$licensetext&"USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF"&@CRLF
$licensetext=$licensetext&"DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD"&@CRLF
$licensetext=$licensetext&"PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),"&@CRLF
$licensetext=$licensetext&"EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF"&@CRLF
$licensetext=$licensetext&"SUCH DAMAGES."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  17. Interpretation of Sections 15 and 16."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  If the disclaimer of warranty and limitation of liability provided"&@CRLF
$licensetext=$licensetext&"above cannot be given local legal effect according to their terms,"&@CRLF
$licensetext=$licensetext&"reviewing courts shall apply local law that most closely approximates"&@CRLF
$licensetext=$licensetext&"an absolute waiver of all civil liability in connection with the"&@CRLF
$licensetext=$licensetext&"Program, unless a warranty or assumption of liability accompanies a"&@CRLF
$licensetext=$licensetext&"copy of the Program in return for a fee."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"                     END OF TERMS AND CONDITIONS"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"            How to Apply These Terms to Your New Programs"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  If you develop a new program, and you want it to be of the greatest"&@CRLF
$licensetext=$licensetext&"possible use to the public, the best way to achieve this is to make it"&@CRLF
$licensetext=$licensetext&"free software which everyone can redistribute and change under these terms."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  To do so, attach the following notices to the program.  It is safest"&@CRLF
$licensetext=$licensetext&"to attach them to the start of each source file to most effectively"&@CRLF
$licensetext=$licensetext&"state the exclusion of warranty; and each file should have at least"&@CRLF
$licensetext=$licensetext&"the ""copyright"" line and a pointer to where the full notice is found."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    <one line to give the program's name and a brief idea of what it does.>"&@CRLF
$licensetext=$licensetext&"    Copyright (C) <year>  <name of author>"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    This program is free software: you can redistribute it and/or modify"&@CRLF
$licensetext=$licensetext&"    it under the terms of the GNU General Public License as published by"&@CRLF
$licensetext=$licensetext&"    the Free Software Foundation, either version 3 of the License, or"&@CRLF
$licensetext=$licensetext&"    (at your option) any later version."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    This program is distributed in the hope that it will be useful,"&@CRLF
$licensetext=$licensetext&"    but WITHOUT ANY WARRANTY; without even the implied warranty of"&@CRLF
$licensetext=$licensetext&"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"&@CRLF
$licensetext=$licensetext&"    GNU General Public License for more details."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    You should have received a copy of the GNU General Public License"&@CRLF
$licensetext=$licensetext&"    along with this program.  If not, see <http://www.gnu.org/licenses/>."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"Also add information on how to contact you by electronic and paper mail."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  If the program does terminal interaction, make it output a short"&@CRLF
$licensetext=$licensetext&"notice like this when it starts in an interactive mode:"&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"    <program>  Copyright (C) <year>  <name of author>"&@CRLF
$licensetext=$licensetext&"    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'."&@CRLF
$licensetext=$licensetext&"    This is free software, and you are welcome to redistribute it"&@CRLF
$licensetext=$licensetext&"    under certain conditions; type `show c' for details."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"The hypothetical commands `show w' and `show c' should show the appropriate"&@CRLF
$licensetext=$licensetext&"parts of the General Public License.  Of course, your program's commands"&@CRLF
$licensetext=$licensetext&"might be different; for a GUI interface, you would use an ""about box""."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  You should also get your employer (if you work as a programmer) or school,"&@CRLF
$licensetext=$licensetext&"if any, to sign a ""copyright disclaimer"" for the program, if necessary."&@CRLF
$licensetext=$licensetext&"For more information on this, and how to apply and follow the GNU GPL, see"&@CRLF
$licensetext=$licensetext&"<http://www.gnu.org/licenses/>."&@CRLF
$licensetext=$licensetext&""&@CRLF
$licensetext=$licensetext&"  The GNU General Public License does not permit incorporating your program"&@CRLF
$licensetext=$licensetext&"into proprietary programs.  If your program is a subroutine library, you"&@CRLF
$licensetext=$licensetext&"may consider it more useful to permit linking proprietary applications with"&@CRLF
$licensetext=$licensetext&"the library.  If this is what you want to do, use the GNU Lesser General"&@CRLF
$licensetext=$licensetext&"Public License instead of this License.  But first, please read"&@CRLF
$licensetext=$licensetext&"<http://www.gnu.org/philosophy/why-not-lgpl.html>."&@CRLF
$licensetext=$licensetext&""&@CRLF
Return $licensetext
EndFunc
